tweak wait logic

diff --git a/.github/actions/update-version/action.yaml b/.github/actions/update-version/action.yaml
--- a/.github/actions/update-version/action.yaml
+++ b/.github/actions/update-version/action.yaml
@@ -71,13 +71,13 @@ runs:
           PR_BUILD_STATUS=""
           while [[ "${PR_BUILD_STATUS}" != "SUCCESS" || "${PR_BUILD_STATUS}" != "FAILED" ]]; do
             PR_BUILD_STATUS=$(gh pr list --head ${{ inputs.version }} --json statusCheckRollup --jq '.[].statusCheckRollup[].conclusion')
-            echo "Waiting for PR build to finish..."
-            if [[ "${PR_BUILD_STATUS}" == "FAILED" ]]; then
-              echo "PR build failed"
-              exit 1
-            fi
+            echo "Current build status: ${PR_BUILD_STATUS}. Waiting for PR build to finish..."
             sleep 10
           done
+           if [[ "${PR_BUILD_STATUS}" == "FAILED" ]]; then
+              echo "PR build failed"
+              exit 1
+          fi
         env:
           GH_TOKEN: ${{ inputs.gha_token }}
 
